import App from "./application/App";
import Entity from "./mvp/entity/Entity";
import Layout from "./mvp/layout/Layout";
import Model from "./mvp/model/Model";
import View from "./mvp/view/View";
import Template from "./mvp/view/Template";
import Page from "./mvp/page/Page";
//import FormView from "./mvp/form/FormStart";
import Presenter from "./mvp/presenters/Presenter";

/**Html Elements */
import html from "./builder/HtmlTemplateBuilder";
import { div } from "./builder/HtmlTemplateBuilder";
import { header } from "./builder/HtmlTemplateBuilder";
import { nav } from "./builder/HtmlTemplateBuilder";
import { section } from "./builder/HtmlTemplateBuilder";
import { footer } from "./builder/HtmlTemplateBuilder";
import { main } from "./builder/HtmlTemplateBuilder";
import { aside } from "./builder/HtmlTemplateBuilder";
import { article } from "./builder/HtmlTemplateBuilder";
import { img } from "./builder/HtmlTemplateBuilder";
import { form } from "./builder/HtmlTemplateBuilder";
import { label } from "./builder/HtmlTemplateBuilder";
import { input } from "./builder/HtmlTemplateBuilder";
import { button } from "./builder/HtmlTemplateBuilder";
import { progress } from "./builder/HtmlTemplateBuilder";
import { ol } from "./builder/HtmlTemplateBuilder";
import { ul } from "./builder/HtmlTemplateBuilder";
import { li } from "./builder/HtmlTemplateBuilder";
import { a } from "./builder/HtmlTemplateBuilder";
import { p } from "./builder/HtmlTemplateBuilder";
import { i } from "./builder/HtmlTemplateBuilder";
import { h1 } from "./builder/HtmlTemplateBuilder";
import { h2 } from "./builder/HtmlTemplateBuilder";
import { h3 } from "./builder/HtmlTemplateBuilder";
import { h4 } from "./builder/HtmlTemplateBuilder";
import { h5 } from "./builder/HtmlTemplateBuilder";
import { h6 } from "./builder/HtmlTemplateBuilder";
import { span } from "./builder/HtmlTemplateBuilder";
import { table } from "./builder/HtmlTemplateBuilder";
import { thead } from "./builder/HtmlTemplateBuilder";
import { tbody } from "./builder/HtmlTemplateBuilder";
import { tfooter } from "./builder/HtmlTemplateBuilder";
import { caption } from "./builder/HtmlTemplateBuilder";
import { tr } from "./builder/HtmlTemplateBuilder";
import { td } from "./builder/HtmlTemplateBuilder";
import { th } from "./builder/HtmlTemplateBuilder";

export default function (config) {
  new App(config);
}

export { Entity };
export { Presenter };
export { Layout };
export { Model };
export { View };
export { Template };
export { Page };
//export { FormView };

/**Html Elements */
export { html };
export { div };
export { header };
export { section };
export { footer };
export { main };
export { aside };
export { article };
export { img };
export { nav };
export { form };
export { input };
export { button };
export { label };
export { progress };
export { ol };
export { ul };
export { li };
export { a };
export { p };
export { i };
export { h1 };
export { h2 };
export { h3 };
export { h4 };
export { h5 };
export { h6 };
export { span };
export { table };
export { thead };
export { tbody };
export { tfooter };
export { caption };
export { tr };
export { td };
export { th };
